# Generated by Django 4.2.7 on 2023-11-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='currency',
            table='currency',
        ),
    ]
